title: Chez Herm JeKyll Docker
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  LAN Dashboard for personal intranet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chezherm.duckdns.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  Herm71

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

# Structure configuration
source: ./source
destination: ./build

# Build Settings
markdown: kramdown
kramdown:
  auto_ids: false

include: ['_pages']

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  #- Gemfile
  #- Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
